# Generated by Django 4.1.4 on 2022-12-13 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 12, 22, 41, 1, 167663)),
        ),
    ]
