# Generated by Django 4.1.4 on 2022-12-13 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 12, 22, 42, 23, 160391)),
        ),
    ]
